#!/bin/bash
#
# Perform necessary chef-marketplace setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

ln -sf /opt/chef-marketplace/bin/chef-marketplace-ctl /usr/bin || error_exit "Cannot link chef-marketplace-ctl in /usr/bin"
chown -Rh 0:0 /opt/chef-marketplace

exit 0
