source "https://rubygems.org"

gem "omnibus-ctl", github: "chef/omnibus-ctl"
gem "chef", "~>13"
gem "pry"
gem "rubocop"
gem "rspec"
gem "chef-marketplace"#, path: File.expand_path("../chef-marketplace-gem")
gem "chefstyle"
