---
branches:
  only:
    - master

dist: trusty
sudo: false

# Set the default language to ruby
language: ruby

cache:
  bundler: true
  directories:
    - $HOME/tools

matrix:
  fast_finish: true

  include:
    - env:
        - NAME=syntax-ruby
      script: 'bundle exec rake spec'
