source "https://rubygems.org"

gem "bundler"

gem "sinatra",         require: "sinatra/base"
gem "sinatra-contrib", require: %w{sinatra/contrib sinatra/config_file sinatra/reloader}
gem "sinatra-flash",   require: "sinatra/flash"
gem "unicorn"
gem "chef", "~>13"
gem "rest-client"
gem "rubyzip"

# Ad-Hoc Debugging
gem "pry-remote"
gem "pry-byebug"

group :development do
  gem "pry"
  gem "rubocop"
  gem "rake"
end
