require_relative "app"

desc "Run the console"
task :console, :env do |_, args|
  ENV["RACK_ENV"] ||= (args[:env] || "development")
  require "pry"
  Pry.start
end

namespace :assets do
  desc "Precompile assets"
  task :precompile do
    system("npm install")
    system("npm run build")
  end
end
