development:
  biscotti:
    message: 'Please enter the Instance ID continue to the web interface. The Instance ID can be found in the AWS Console.'
    token: '12345'
    uuid_type: 'Instance ID'
    uuid: 'i-1234abcd'
    doc_href: "https://docs.chef.io/aws_marketplace.html"
    cloud_marketplace: "AWS Marketplace"
    auth_required: true
    credentials:
      admin_password: 'AUTOMATEADMINPASSWORD'

production:
  biscotti:
    message: 'Please enter the Instance ID continue to the web interface'
    token: '12345'
    uuid_type: 'Instance ID'
    uuid: 'i-1234abcd'
    doc_href: "https://docs.chef.io/aws_marketplace.html"
    cloud_marketplace: "AWS Marketplace"
    auth_required: true
    credentials:
      admin_password: 'AUTOMATEADMINPASSWORD'
