name              "chef-marketplace"
maintainer        "Chef Software, Inc."
maintainer_email  "partnereng@chef.io"
license           "Apache 2.0"
description       "Sets up the Chef server Marketplace additions"
long_description  "Sets up the Chef server Marketplace additions"
version           "0.0.1"
supports          "centos"

depends "motd"
depends "chef-ingredient"
depends "yum-centos"
depends "hostname"
depends "enterprise"
