name              'chef-marketplace'
maintainer        'Chef Software, Inc.'
maintainer_email  'partnereng@chef.io'
license           'Apache 2.0'
description       'Sets up HA AWS for the chef server'
long_description  'Sets up HA AWS for the chef server'
version           '0.0.1'
supports          'centos'
