# Documentation available at http://expeditor-docs.es.chef.io/

product_key: marketplace

pipelines:
  - omnibus/release
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Version: Skip Bump"
            - "Expeditor: Skip All"
      - built_in:update_changelog:
          ignore_labels:
            - "Changelog: Skip Update"
            - "Expeditor: Skip All"
      - trigger_pipeline:omnibus/release:
          ignore_labels:
            - "Omnibus: Skip Build"
            - "Expeditor: Skip All"
          only_if: built_in:bump_version
  
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:promote_artifactory_artifact

artifact_actions:
  promoted_to_stable:
    - built_in:rollover_changelog
    - built_in:create_github_release
    - built_in:notify_chefio_slack_channels

artifact_channels:
  - unstable
  - current
  - stable
