#!/usr/bin/env rake

require "rake"
require "rspec"
require "rspec/core"
require "rspec/core/rake_task"
require "bundler"
require "bundler/gem_tasks"
require "chefstyle"
require "rubocop/rake_task"

desc "Default task to run spec suite"
task default: %w{spec rubocop}

desc "Run spec suite"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.pattern = FileList["spec/**/*_spec.rb"]
end

desc "Run RSpec with code coverage"
task :coverage do
  ENV["COVERAGE"] = "true"
  Rake::Task["spec"].execute
end

desc "Run Rubocop style checks"
RuboCop::RakeTask.new do |task|
  task.fail_on_error = true
  task.options << "--display-cop-names"
end
